# Generated by Django 5.0.4 on 2024-04-07 06:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_alter_stockin_date_added_alter_stockin_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='inventory_management.product'),
        ),
    ]
